"""test

Revision ID: 1952ba85b00c
Revises:
Create Date: 2025-04-18 19:32:55.839421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1952ba85b00c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_google_fitness_api_access_tokens_user_id",
        table_name="google_fitness_api_access_tokens",
    )
    op.create_index(
        op.f("ix_google_fitness_api_access_tokens_user_id"),
        "google_fitness_api_access_tokens",
        ["user_id"],
        unique=True,
    )
    op.drop_index(
        "ix_google_fitness_api_refresh_tokens_user_id",
        table_name="google_fitness_api_refresh_tokens",
    )
    op.create_index(
        op.f("ix_google_fitness_api_refresh_tokens_user_id"),
        "google_fitness_api_refresh_tokens",
        ["user_id"],
        unique=True,
    )
    op.add_column(
        "users",
        sa.Column(
            "need_to_refresh_google_api_token",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "need_to_refresh_google_api_token")
    op.drop_index(
        op.f("ix_google_fitness_api_refresh_tokens_user_id"),
        table_name="google_fitness_api_refresh_tokens",
    )
    op.create_index(
        "ix_google_fitness_api_refresh_tokens_user_id",
        "google_fitness_api_refresh_tokens",
        ["user_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_google_fitness_api_access_tokens_user_id"),
        table_name="google_fitness_api_access_tokens",
    )
    op.create_index(
        "ix_google_fitness_api_access_tokens_user_id",
        "google_fitness_api_access_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
