"""added integrations

Revision ID: 20f62bbe1d51
Revises: 1952ba85b00c
Create Date: 2025-04-25 15:24:27.966910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f62bbe1d51'
down_revision: Union[str, None] = '1952ba85b00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('google_fitness_api', 'google_health_api', name='integration_source'), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_integrations_id'), 'user_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_index(op.f('ix_user_integrations_id'), table_name='user_integrations')
    op.drop_table('user_integrations')
    # ### end Alembic commands ###
