"""upd attr

Revision ID: 6bc611ef185f
Revises: a60abaab0695
Create Date: 2025-05-25 13:41:33.056388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bc611ef185f"
down_revision: Union[str, None] = "a60abaab0695"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "test_user", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "test_user", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
