"""added date

Revision ID: 965dbfe97374
Revises: 6bc611ef185f
Create Date: 2025-06-16 23:46:54.653741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "965dbfe97374"
down_revision: Union[str, None] = "6bc611ef185f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birth_date", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("gender", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    op.drop_column("users", "birth_date")
    # ### end Alembic commands ###
