"""added date

Revision ID: d9a4cd341347
Revises: 60864fdd638e
Create Date: 2025-06-17 00:09:48.940574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9a4cd341347"
down_revision: Union[str, None] = "60864fdd638e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "test_user", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "birth_date",
            sa.DateTime(),
            server_default=sa.text("'2000-01-01 00:00:00+00'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "gender", sa.String(), server_default=sa.text("'male'"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    op.drop_column("users", "birth_date")
    op.drop_column("users", "test_user")
    # ### end Alembic commands ###
