apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: hse-coursework-health
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP